#!/usr/bin/python
# Author: Jason J. Herne
from gi.repository import Gtk, GObject
from ViziGrepWindow import ViziGrepWindow
from Preferences import Preferences

GObject.threads_init() 
vgw = ViziGrepWindow(Preferences('vizigrep'))
vgw.activate()
Gtk.main()
