#!/usr/bin/python
# Copyright: Jason J. Herne (hernejj@gmail.com)
# License: GPL-v2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt)
from gi.repository import Gtk, GObject
from ViziGrepWindow import ViziGrepWindow
from Preferences import Preferences

GObject.threads_init() 
vgw = ViziGrepWindow(Preferences('vizigrep'))
vgw.activate()
Gtk.main()
